
	<title>Turquia.com | Business To Business</title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />	
	<meta http-equiv="cache-control" content="no-cache" />
  <meta http-equiv="Expires" content="-1" />
	<meta name="keywords" content="RETUR TOURISM, TURQUIA, TURKEY" />
	<meta name="description" content="RETUR" />
	<meta name="Author" content="by Caretta.Net" />
	<meta name="Copyright" content="RETUR" />
	<meta name="reply-to" content="info@turquia.com" />
	<meta name="robots" content="ALL" />
	<meta name="revisit-after" content="1" />
	<meta name="Rating" content="General" />
	<meta name="Distribution" content="Global" />
	<meta name="Classification" content="TURQUIA" 
	<meta name="Pragma" content="no-cache" />